Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/SignalException:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/PredicateName:
  Enabled: false
