source 'https://rubygems.org'

gem 'rake', '~> 12.0.0'
gem 'rspec', '~> 3.5'
gem 'rubocop', '~> 0.47.1'
gem 'capybara', '~> 2.12.1'
gem 'capybara-webkit', '~> 1.12.0'
gem 'capybara-screenshot', '~> 1.0.14'
